# Generated by Django 4.0 on 2023-08-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JUUSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOILST', models.CharField(max_length=30)),
                ('MOJUSO1', models.CharField(max_length=100)),
                ('MAPS_X', models.FloatField()),
                ('MAPS_Y', models.FloatField()),
                ('UJONG', models.CharField(max_length=1)),
                ('SMART', models.BooleanField(default=False)),
                ('PRICE', models.IntegerField()),
            ],
        ),
    ]
