# Generated by Django 4.0 on 2023-08-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JUUSO',
            new_name='Station',
        ),
    ]
